[project]
name = "kazakh-identification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=2.3.13",
    "fastapi[standard]>=0.124.4",
]
